### ISSUE TITLE
Are some tests supposed to fail?

### ISSUE THREAD

**Issue by why-el** [rails/rails-dev-box#102]
Hey, 

Given that this repo is supposed to produce a complete environment in which Rails tests can run smoothly, does it make sense that some of them fail for me? Even if all of them run inside Vagrant where everything is supposed to be in place?

**Comment by fxn** [comment]
Ideally they should all pass. What's failing?

**Comment by why-el** [comment]
Here is one:

![screen shot 2015-05-21 at 4 48 37 pm](https://cloud.githubusercontent.com/assets/1326771/7751246/36b442fe-ffd9-11e4-8ab5-7cf553f1825c.png)

And another:

![screen shot 2015-05-21 at 4 49 22 pm](https://cloud.githubusercontent.com/assets/1326771/7751251/3e8f9794-ffd9-11e4-8ad7-5d6094f5ed25.png)

At the end it's reported `Errors in actionview, activerecord, railties`.

**Comment by fxn** [comment]
Te second one seems to mean there's not enough RAM. The first one could be a temporary hiccup in the test suite. @rafaelfranca does that one ring a bell?

**Comment by why-el** [comment]
Yes, I actually increased my vm RAM to 3GB, with no results.

**Comment by why-el** [comment]
And the first one fails consistently for me actually.

**Comment by rafaelfranca** [comment]
No, sorry. Travis and locally are passing all tests.

**Comment by why-el** [comment]
@rafaelfranca mind if I take a look at your Vagrant file?

**Comment by rafaelfranca** [comment]
I don't use vagrant. Everything runs in my Mac OS X machine. I thought this error were related to linux but travis run on linux, so it maybe something on this setup.

**Comment by fxn** [comment]
:+1: thanks Rafael, I'll try with Vagrant.

**Comment by fxn** [comment]
I have fixed the one in AV. Can reproduce the ones about memory, going to investigate those later.

**Comment by why-el** [comment]
Brilliant. Thanks for the good work Xavier.

On Thursday, May 21, 2015, Xavier Noria <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I have fixed the one in AV. Can reproduce the ones about memory, going to
> investigate those later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails-dev-box/issues/102#issuecomment-104402265>
> .
>


-- 
Mohamed Wael Khobalatte

**Comment by yoongkang** [comment]
@fxn, the changes broke my tests locally. I'm on Mac OS X and have a case-insensitive file system. The helper method in the test suite correctly detects I am on a case-insensitive filesystem, but still raises a TemplateMissing exception.

Reverting the commit got it working again locally. Just thought you might like to know. 

I don't have Vagrant at the moment so I can't see what was going on in the original problem, but I could have a dig around later when I have the time.

**Comment by fxn** [comment]
@yoongkang interesting! let's see what you find.

**Comment by laiso** [comment]
@fxn I saw it too.
`PathResolver#find_template_paths`  `deals with case-insensitive file systems.` ?
https://github.com/rails/rails/blob/77a7c4bf7d2ed73cbc2554ef9f0514f6191b2658/actionview/lib/action_view/template/resolver.rb

**Comment by MGerrior** [comment]
@why-el I recently ran into the memory issues setting up the dev environment myself. I was able to work around them by upping the vm RAM to 8GB (host has 16GB, so 8GB for the guest isn't too much of an issue). Not sure how much memory is necessary to get around it, but it seems to be somewhere between 3GB and 8GB if that helps.

**Comment by why-el** [comment]
Thanks. Did all tests pass after that? That seems to be the issue still.

**Comment by MGerrior** [comment]
Yes, they were all passing after that for me, though I never saw the `actionview` errors you encountered (using OSX as the host). I'm not sure it will resolve anything for you, but I believe the base box for this (`ubuntu/trusty64`) has been updated since you first opened this issue. You could try destroying your box and running `vagrant box update` to get the latest version of `ubuntu/trusty64` and then provision the box with the new version and increase RAM (or just update your ram from the VirtualBox GUI).

**Comment by why-el** [comment]
Yep I will do that. Hopefully 5-6GB should do it (host is 8GB).

**Comment by glUk-skywalker** [comment]
Hm guyz. Why did I get this mails

**Comment by vladimirich** [comment]
I ran into the problem with first test. Is it fixed, or not? 
I use Vagrant box for test running.

**Comment by meinac** [comment]
I've encountered with same issue while working with source of Android OS. It's impossible to build the Android from it's source on case-insensitive file systems. But they have a documentation about it [here](https://source.android.com/source/initializing.html#setting-up-a-mac-os-x-build-environment). Even tough ubuntu has case-sensitive file system by default, Vagrant mimics the hosted file system for shared folders. This means if your host OS has case-insensitive file system then your shared folder will be mounted as case-insensitive. But rest of the virtual machine will be case-sensitive. You can test it by creating two files like `foo.txt` and `Foo.txt` in your user's home directory. @rafaelfranca I think your OS X has case-sensitive file system so this is why this tests pass as expected on your local machine.

One workaround maybe using a file server like [samba](https://www.samba.org/). Don't forget to move source of rails from shared folder to another one on your guest OS. Also not that, symlink does not work! Then configure your samba server and have fun with case-sensitive file system.

But I think instead of a workarounds these tests shouldn't fail on case-insensitive file systems. There was [a commit](https://github.com/rails/rails/commit/d345ce9630ce4c01bc81a09fb015e7bd935600ad) to fix the problem made by @fxn but it's reverted by @matthewd and I couldn't find the reason behind of this revert.

**Comment by sobrinho** [comment]
@fxn I think this can be closed since the issue was detected and the memory is configurable now.

**Comment by fxn** [comment]
Thanks @sobrinho, this cleanup you're doing is much needed ❤️ .
