### ISSUE TITLE
Gemfile.lock is modified on a clean install

### ISSUE THREAD

**Issue by murdoch** [rails/rails-dev-box#107]
I cloned the dev-box, and ran `vagrant up --provision`. I then navigated to /vagrant/rails and was surprised to find `git status` return the following:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Gemfile.lock
```

I would expect `git status` to tell me that my branch is up to date, nothing to commit etc.

Steps to reproduce:

- git clone git@github.com:rails/rails-dev-box.git
- cd rails-dev-box
- vagrant up --provision
- vagrant ssh
- cd /vagrant/rails
- git status
  - observe output informs us that Gemfile.lock has been modified

Does the rails core team advise using the VM? Or should I just set everything up manually on my system?

**Comment by fxn** [comment]
This is a session I just ran:

```
fxn@yeager:~/prj $ git clone git@github.com:rails/rails-dev-box.git
Cloning into 'rails-dev-box'...
...
fxn@yeager:~/prj $ cd rails-dev-box/
fxn@yeager:~/prj/rails-dev-box (master)$ git clone git@github.com:rails/rails.git
Cloning into 'rails'...
...
fxn@yeager:~/prj/rails-dev-box (master)$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
...
fxn@yeager:~/prj/rails-dev-box (master)$ vagrant ssh
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-55-generic x86_64)
...
vagrant@rails-dev-box:~$ cd /vagrant/rails
vagrant@rails-dev-box:/vagrant/rails$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

Since this stuff is deterministic, I am going to close the issue as "works for me".

Regarding your question, yes this VM is created and maintained by core and its purpose is to provide a dev environment for Rails contributors. Thus, [we certainly recommend it](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#setting-up-a-development-environment).

Note this is for Rails contributors, not for Rails application programmers. It is only thought for people working on patches to Rails.

**Comment by murdoch** [comment]
Thanks Xavier, I will try it out again tonight on a different machine.

Regarding your last point, I plan to use the dev-box for its intended purpose, and hope to contributing some patches to rails.

Thanks again.

**Comment by fxn** [comment]
@murdoch awesome :smile:.
