### ISSUE TITLE
ls: cannot access /vagrant: No such file or directory

### ISSUE THREAD

**Issue by hopewise** [rails/rails-dev-box#83]
I have followed all instructions, but when I do

vagrant@vagrant-ubuntu-trusty-32:~$ ls /vagrant
I get:
ls: cannot access /vagrant: No such file or directory

Although:
vagrant@vagrant-ubuntu-trusty-32:~$ cd ..
vagrant@vagrant-ubuntu-trusty-32:/home$ dir
ubuntu  vagrant
vagrant@vagrant-ubuntu-trusty-32:/home$ cd vagrant
vagrant@vagrant-ubuntu-trusty-32:~$ ls
vagrant@vagrant-ubuntu-trusty-32:~$

it seems vagrant is empty at my VM, although I did clone my repo into rails-dev-box at host

Any idea?

**Comment by BMorearty** [comment]
I had the exact same problem (on Mac OSX Yosemite), with the exact same symptoms--no access to /vagrant, and a prompt that said `vagrant@vagrant-ubuntu-trusty-32:~$`. 

I believe it stemmed from having an older version of VirtualBox when I installed the Rails box. 

The fix for me was:

1. Install the latest version of VirtualBox (NOTE: go to the website! The "Check for Updates" menu says there are no updates even when there are.)
2. vagrant halt
3. vagrant destroy
4. vagrant up
