### ISSUE TITLE
bootstrap.sh installs Ruby 2.2.0, but Ruby 2.2.1 is required.

### ISSUE THREAD

**Issue by brookr** [rails/rails-dev-box#97]
Running `rails-dev-box`, and following instructions from the contributors guide, I hit this error when trying to use Rails:
```
vagrant@rails-dev-box:/vagrant/rails$ bundle exec rails new

    Rails 5 requires to run on Ruby 2.2.1 or newer.

    You're running
      ruby 2.2.0p0 (2014-12-25 revision 49005) [i386-linux-gnu]

    Please upgrade to Ruby 2.2.1 or newer to continue.
```

It seems 2.2.1 isn't yet available from `apt-get`, so should bootstrap.sh be updated to install ruby from source? I'd be happy to put a PR together.

**Comment by fxn** [comment]
This is so exceptional that I believe we can leave this issue open so that people see it's known, and wait until Brightbox releases the new packages. Better than touching *bootstrap.sh*. Meanwhile people can install a version manager or whatever temporarily.

Going to cc John just so that he is aware of this @johnl (but no hurry man! whenever you guys release 2.2.1 is going to be fine :).

**Comment by johnl** [comment]
Thanks for the nudge @fxn. 2.2.1 packages now building for Precise, Trusty and Utopic and will be available in the experimental repo for testing. I'll copy to ruby-ng once tested.

https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng-experimental/

**Comment by brookr** [comment]
Thanks so much, gents!

**Comment by johnl** [comment]
Ruby 2.2.1 packages are available in the ruby-ng release repository now btw!

**Comment by fxn** [comment]
Thanks a lot John!

**Comment by fxn** [comment]
I am closing this ticket because it was about 2.2.1 and 2.2.1 gets installed. But we are at square one because 2.2.2 is now required, going to open another issue for that one.
